In [14]:
import pandas as pd
import numpy as np
import os

#Carga de archivos
base_path =r"C:\Users\Nefi\OneDrive\Documentos\09-EBAC\Python\Referencia\Proyecto"
files = {
    "dim_category": os.path.join(base_path, "DIM_CATEGORY.csv"),
    "dim_product": os.path.join(base_path, "DIM_PRODUCT.csv"),
    "dim_segment": os.path.join(base_path, "DIM_SEGMENT.csv"),
    "dim_calendar": os.path.join(base_path, "DIM_CALENDAR.csv"),
    "fact_sales": os.path.join(base_path, "FACT_SALES.csv")
}

In [15]:
#Documentos de información utilizados
dim_category = pd.read_csv(files["dim_category"], encoding='latin1')
dim_product  = pd.read_csv(files["dim_product"], encoding='latin1')
dim_segment  = pd.read_csv(files["dim_segment"], encoding='latin1')
dim_calendar = pd.read_csv(files["dim_calendar"], encoding='latin1')
fact_sales   = pd.read_csv(files["fact_sales"], encoding='latin1')

In [16]:
#Exploración de datos
def quick_info(df, name):
    print(f"\n==== {name} ====")
    print("shape:", df.shape)
    print("columns:", df.columns.tolist())
    display(df.head())
    print(df.info())
    print(df.describe(include='all').T)

quick_info(dim_category, "DIM_CATEGORY")
quick_info(dim_product,  "DIM_PRODUCT")
quick_info(dim_segment,  "DIM_SEGMENT")
quick_info(dim_calendar, "DIM_CALENDAR")
quick_info(fact_sales,   "FACT_SALES")

==== DIM_CATEGORY ====
shape: (5, 2)
columns: ['ID_CATEGORY', 'CATEGORY']

   ID_CATEGORY                    CATEGORY
0            1  FABRIC TREATMENT and SANIT
1            2                   AIR CARE
2            3                LAVAVAJILLAS
3            4            MEGA SUPERFICIES
4            5         LAVATORY CARE & BRC

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID_CATEGORY  5 non-null      int64
 1   CATEGORY     5 non-null      object
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes
None
            count unique                         top freq mean       std  min  \
ID_CATEGORY   5.0    NaN                         NaN  NaN  3.0  1.581139  1.0
CATEGORY        5      5  FABRIC TREATMENT and SANIT    1  NaN       NaN  NaN

             25%  50%  75%  max
ID_CATEGORY  2.0  3.0  4.0  5.0
CATEGORY     NaN  NaN  NaN  NaN

==== DIM_PRODUCT ====
shape: (505, 10)
columns: ['ID_ITEM', 'ITEM', 'MANUFACTURER', 'BRAND', 'ITEM_DESCRIPTION', 'CATEGORY', 'FORMAT', 'ATTR1', 'ATTR2', 'ATTR3']

,ID_ITEM,ITEM,MANUFACTURER,BRAND,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,1,0000075000592,INDS. ALEN,CLORALEX,CLORALEX EL RENDIDOR BOT.PLAST. 250ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
1,2,0000075000608,INDS. ALEN,CLORALEX,CLORALEX EL RENDIDOR BOT.PLAST. 500ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
2,3,0000075000615,INDS. ALEN,CLORALEX,CLORALEX EL RENDIDOR BOT.PLAST. 950ML NAL. 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
3,4,0000075000622,INDS. ALEN,CLORALEX,CLORALEX EL RENDIDOR BOT.PLAST. 2000ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO
4,5,0000075000639,INDS. ALEN,CLORALEX,CLORALEX EL RENDIDOR BOT.PLAST. 3750ML NAL 000...,1,LIQUIDO,CLORO,CLORO,NO DEFINIDO

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID_ITEM           505 non-null    int64
 1   ITEM              503 non-null    object
 2   MANUFACTURER      505 non-null    object
 3   BRAND             505 non-null    object
 4   ITEM_DESCRIPTION  505 non-null    object
 5   CATEGORY          505 non-null    int64
 6   FORMAT            505 non-null    object
 7   ATTR1             499 non-null    object
 8   ATTR2             505 non-null    object
 9   ATTR3             499 non-null    object
dtypes: int64(2), object(8)
memory usage: 39.6+ KB
None
                  count unique  \
ID_ITEM           505.0    NaN
ITEM                503    503
MANUFACTURER        505     20
BRAND               505     33
ITEM_DESCRIPTION    505    505
CATEGORY          505.0    NaN
FORMAT              505      5
ATTR1               499      4
ATTR2               505      3
ATTR3               499     15

                                                                top freq  \
ID_ITEM                                                         NaN  NaN
ITEM                                               7502240948188BP1    1
MANUFACTURER                                                RECKITT  128
BRAND                                                      CLORALEX  115
ITEM_DESCRIPTION  CLOROX BLANQ930M+MMBLANQINOD709M+MMFIBRAULTRA1...    1
CATEGORY                                                        NaN  NaN
FORMAT                                                      LIQUIDO  326
ATTR1                                                         CLORO  243
ATTR2                                                         CLORO  249
ATTR3                                                   NO DEFINIDO  137

                   mean         std  min    25%    50%    75%    max
ID_ITEM           253.0  145.925209  1.0  127.0  253.0  379.0  505.0
ITEM                NaN         NaN  NaN    NaN    NaN    NaN    NaN
MANUFACTURER        NaN         NaN  NaN    NaN    NaN    NaN    NaN
BRAND               NaN         NaN  NaN    NaN    NaN    NaN    NaN
ITEM_DESCRIPTION    NaN         NaN  NaN    NaN    NaN    NaN    NaN
CATEGORY            1.0         0.0  1.0    1.0    1.0    1.0    1.0
FORMAT              NaN         NaN  NaN    NaN    NaN    NaN    NaN
ATTR1               NaN         NaN  NaN    NaN    NaN    NaN    NaN
ATTR2               NaN         NaN  NaN    NaN    NaN    NaN    NaN
ATTR3               NaN         NaN  NaN    NaN    NaN    NaN    NaN

==== DIM_SEGMENT ====
shape: (53, 7)
columns: ['ID_SEGMENT', 'SEGMENT', 'CATEGORY', 'ATTR1', 'ATTR2', 'ATTR3', 'FORMAT']

   ID_SEGMENT SEGMENT  CATEGORY  ATTR1  ATTR2      ATTR3   FORMAT
0           1  BLEACH         1  CLORO  CLORO    BAMBINO  LIQUIDO
1           2  BLEACH         1  CLORO  CLORO  GERMICIDA  LIQUIDO
2           3  BLEACH         1  CLORO  CLORO   MASCOTAS  LIQUIDO
3           4  BLEACH         1  CLORO  CLORO  MULTIUSOS      GEL
4           5  BLEACH         1  CLORO  CLORO  MULTIUSOS  LIQUIDO

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID_SEGMENT  53 non-null     int64
 1   SEGMENT     53 non-null     object
 2   CATEGORY    53 non-null     int64
 3   ATTR1       53 non-null     object
 4   ATTR2       53 non-null     object
 5   ATTR3       52 non-null     object
 6   FORMAT      53 non-null     object
dtypes: int64(2), object(5)
memory usage: 3.0+ KB
None
           count unique               top freq  mean        std  min   25%  \
ID_SEGMENT  53.0    NaN               NaN  NaN  27.0  15.443445  1.0  14.0
SEGMENT       53      7      LIQUID & GEL   16   NaN        NaN  NaN   NaN
CATEGORY    53.0    NaN               NaN  NaN   1.0        0.0  1.0   1.0
ATTR1         53      4       SAFE BLEACH   27   NaN        NaN  NaN   NaN
ATTR2         53      7  FABRIC TREATMENT   37   NaN        NaN  NaN   NaN
ATTR3         52     16            BLANCO    7   NaN        NaN  NaN   NaN
FORMAT        53      5           LIQUIDO   24   NaN        NaN  NaN   NaN

             50%   75%   max
ID_SEGMENT  27.0  40.0  53.0
SEGMENT      NaN   NaN   NaN
CATEGORY     1.0   1.0   1.0
ATTR1        NaN   NaN   NaN
ATTR2        NaN   NaN   NaN
ATTR3        NaN   NaN   NaN
FORMAT       NaN   NaN   NaN

==== DIM_CALENDAR ====
shape: (156, 5)
columns: ['WEEK', 'YEAR', 'MONTH', 'WEEK_NUMBER', 'DATE']

     WEEK  YEAR  MONTH  WEEK_NUMBER        DATE
0  ene-21  2021      1            1  2021-01-10
1  feb-21  2021      1            2  2021-01-17
2  mar-21  2021      1            3  2021-01-24
3  abr-21  2021      1            4  2021-01-31
4  may-21  2021      2            5  2021-02-07

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   WEEK         156 non-null    object
 1   YEAR         156 non-null    int64
 2   MONTH        156 non-null    int64
 3   WEEK_NUMBER  156 non-null    int64
 4   DATE         156 non-null    object
dtypes: int64(3), object(2)
memory usage: 6.2+ KB
None
             count unique         top freq      mean        std     min  \
WEEK           156    156      ene-21    1       NaN        NaN     NaN
YEAR         156.0    NaN         NaN  NaN    2022.0   0.819126  2021.0
MONTH        156.0    NaN         NaN  NaN  6.487179   3.459419     1.0
WEEK_NUMBER  156.0    NaN         NaN  NaN      26.5  15.056667     1.0
DATE           156    156  2021-01-10    1       NaN        NaN     NaN

                25%     50%     75%     max
WEEK            NaN     NaN     NaN     NaN
YEAR         2021.0  2022.0  2023.0  2023.0
MONTH          3.75     6.5    9.25    12.0
WEEK_NUMBER   13.75    26.5   39.25    52.0
DATE            NaN     NaN     NaN     NaN

==== FACT_SALES ====
shape: (122002, 7)
columns: ['ID_SALES', 'WEEK', 'ITEM_CODE', 'REGION', 'TOTAL_UNIT_SALES', 'TOTAL_VALUE_SALES', 'TOTAL_UNIT_AVG_WEEKLY_SALES']

,ID_SALES,WEEK,ITEM_CODE,REGION,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES
0,1,34-22,7501058792808BP2,TOTAL AUTOS AREA 5,0.006,0.139,1.000
1,2,34-22,7.50106E+12,TOTAL AUTOS AREA 5,0.487,116.519,2.916
2,3,34-22,7.70263E+12,TOTAL AUTOS AREA 5,1.391,68.453,5.171
3,4,34-22,7.50106E+12,TOTAL AUTOS AREA 5,0.022,1.481,1.833
4,5,34-22,7.50106E+12,TOTAL AUTOS AREA 5,2.037,182.839,5.375

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122002 entries, 0 to 122001
Data columns (total 7 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   ID_SALES                     122002 non-null  int64
 1   WEEK                         122002 non-null  object
 2   ITEM_CODE                    122002 non-null  object
 3   REGION                       122002 non-null  object
 4   TOTAL_UNIT_SALES             122002 non-null  float64
 5   TOTAL_VALUE_SALES            122002 non-null  float64
 6   TOTAL_UNIT_AVG_WEEKLY_SALES  122002 non-null  float64
dtypes: float64(3), int64(1), object(3)
memory usage: 6.5+ MB
None
                                count unique                          top  \
ID_SALES                     122002.0    NaN                          NaN
WEEK                           122002     80                       jul-22
ITEM_CODE                      122002     84                  7.50106E+12
REGION                         122002      7  TOTAL AUTOS SCANNING MEXICO
TOTAL_UNIT_SALES             122002.0    NaN                          NaN
TOTAL_VALUE_SALES            122002.0    NaN                          NaN
TOTAL_UNIT_AVG_WEEKLY_SALES  122002.0    NaN                          NaN

                              freq       mean           std    min       25%  \
ID_SALES                       NaN    61001.5  35219.088108    1.0  30501.25
WEEK                          1629        NaN           NaN    NaN       NaN
ITEM_CODE                    22334        NaN           NaN    NaN       NaN
REGION                       20990        NaN           NaN    NaN       NaN
TOTAL_UNIT_SALES               NaN   3.211097     14.496009    0.0     0.063
TOTAL_VALUE_SALES              NaN  90.513761    350.236505  0.001     2.662
TOTAL_UNIT_AVG_WEEKLY_SALES    NaN  10.099904     22.650142  0.042     2.316

                                 50%       75%        max
ID_SALES                     61001.5  91501.75   122002.0
WEEK                             NaN       NaN        NaN
ITEM_CODE                        NaN       NaN        NaN
REGION                           NaN       NaN        NaN
TOTAL_UNIT_SALES               0.367      1.52    504.681
TOTAL_VALUE_SALES             16.812   62.9615  12236.759
TOTAL_UNIT_AVG_WEEKLY_SALES   3.9935     8.898      794.0

In [23]:
# Limpieza strings en las dims y facts
dim_category = clean_strings(dim_category)
dim_product  = clean_strings(dim_product)
dim_segment  = clean_strings(dim_segment)
dim_calendar = clean_strings(dim_calendar)
fact_sales   = clean_strings(fact_sales)

In [24]:
# Lista de dataframes
tables = {
    "dim_cat": dim_category,
    "dim_prod": dim_product,
    "dim_seg": dim_segment,
    "dim_cal": dim_calendar,
    "fact_sales": fact_sales
}

In [25]:
# Función de limpieza general
def clean_df(df):
    # 1. Estandarizar nombres de columnas
    df.columns = df.columns.str.strip().str.upper()
    
    # 2. Quitar espacios en datos tipo string
    for col in df.select_dtypes(include=["object"]):
        df[col] = df[col].astype(str).str.strip()

    # 3. Eliminar duplicados
    df = df.drop_duplicates()

    return df

# Aplicar la función
dim_category = clean_df(dim_category)
dim_product = clean_df(dim_product)
dim_segment = clean_df(dim_segment)
dim_calendar = clean_df(dim_calendar)
fact_sales = clean_df(fact_sales)

In [51]:
#Para CATEGORY convertimos el ID a enteros
dim_category["ID_CATEGORY"] = pd.to_numeric(dim_category["ID_CATEGORY"], errors="coerce")
dim_category = dim_category.dropna(subset=["ID_CATEGORY"])

In [57]:
#Para PRODUCT
# Convertir ITEM a string para unir con SALES
dim_product["ITEM"] = dim_product["ITEM"].astype(str).str.replace(".0","")

# Convertir ID_ITEM a numérico
dim_product["ID_ITEM"] = pd.to_numeric(dim_product["ID_ITEM"], errors="coerce")

# Rellenar NO DEFINIDO con NaN
dim_product.replace("NO DEFINIDO", np.nan, inplace=True)

#Convertir CATEGORY A string para unir con SALES
dim_product['CATEGORY'] = dim_product['CATEGORY'].astype(str)

In [58]:
#Para SEGMENT se hace la relación con PRODUCT
dim_segment["ID_SEGMENT"] = pd.to_numeric(dim_segment["ID_SEGMENT"], errors="coerce")

In [59]:
#Para CALENDAR se ajustan los formatos de fecha para que se puedan utilizar correctamente
dim_calendar["DATE"] = pd.to_datetime(dim_calendar["DATE"], format='mixed', dayfirst=True)

dim_calendar["WEEK_NUMBER"] = pd.to_numeric(dim_calendar["WEEK_NUMBER"], errors="coerce")
dim_calendar["YEAR"] = pd.to_numeric(dim_calendar["YEAR"], errors="coerce")

In [60]:
#Para SALES
# ITEM_CODE a string para unir con PRODUCT
fact_sales["ITEM_CODE"] = fact_sales["ITEM_CODE"].astype(str).str.replace(".0","")

# Convertir columnas numéricas
num_cols = ["TOTAL_UNIT_SALES", "TOTAL_VALUE_SALES", "TOTAL_UNIT_AVG_WEEKLY_SALES"]

for col in num_cols:
    fact_sales[col] = pd.to_numeric(fact_sales[col], errors="coerce")
#Convertir CATEGORY A string para unir con PRODUCT
dim_product['CATEGORY'] = dim_product['CATEGORY'].astype(str)

In [61]:
#Unión de tablas
#SALES con Product
sales_prod = fact_sales.merge(
    dim_product,
    how="left",
    left_on="ITEM_CODE",
    right_on="ITEM"
)
sales_prod_cat = sales_prod.merge(
    dim_category,
    how="left",
    left_on="CATEGORY",
    right_on="CATEGORY"
)
final_df = sales_prod_cat.merge(
    dim_calendar,
    how="left",
    on="WEEK"
)

In [62]:
#Revisión de la información final
print(final_df.info())
print(final_df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122002 entries, 0 to 122001
Data columns (total 22 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   ID_SALES                     122002 non-null  int64
 1   WEEK                         122002 non-null  object
 2   ITEM_CODE                    122002 non-null  object
 3   REGION                       122002 non-null  object
 4   TOTAL_UNIT_SALES             122002 non-null  float64
 5   TOTAL_VALUE_SALES            122002 non-null  float64
 6   TOTAL_UNIT_AVG_WEEKLY_SALES  122002 non-null  float64
 7   ID_ITEM                      9193 non-null    float64
 8   ITEM                         9193 non-null    object
 9   MANUFACTURER                 9193 non-null    object
 10  BRAND                        9193 non-null    object
 11  ITEM_DESCRIPTION             9193 non-null    object
 12  CATEGORY                     9193 non-null    object
 13  FORMAT                       9193 non-null    object
 14  ATTR1                        9193 non-null    object
 15  ATTR2                        9193 non-null    object
 16  ATTR3                        7849 non-null    object
 17  ID_CATEGORY                  0 non-null       float64
 18  YEAR                         122002 non-null  int64
 19  MONTH                        122002 non-null  int64
 20  WEEK_NUMBER                  122002 non-null  int64
 21  DATE                         122002 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(5), int64(4), object(12)
memory usage: 20.5+ MB
None
   ID_SALES   WEEK         ITEM_CODE              REGION  TOTAL_UNIT_SALES  \
0         1  34-22  7501058792808BP2  TOTAL AUTOS AREA 5             0.006
1         2  34-22       7.50106E+12  TOTAL AUTOS AREA 5             0.487
2         3  34-22       7.70263E+12  TOTAL AUTOS AREA 5             1.391
3         4  34-22       7.50106E+12  TOTAL AUTOS AREA 5             0.022
4         5  34-22       7.50106E+12  TOTAL AUTOS AREA 5             2.037

   TOTAL_VALUE_SALES  TOTAL_UNIT_AVG_WEEKLY_SALES  ID_ITEM              ITEM  \
0              0.139                        1.000    313.0  7501058792808BP2
1            116.519                        2.916      NaN               NaN
2             68.453                        5.171      NaN               NaN
3              1.481                        1.833      NaN               NaN
4            182.839                        5.375      NaN               NaN

  MANUFACTURER  ... CATEGORY FORMAT        ATTR1             ATTR2 ATTR3  \
0      RECKITT  ...        1  POLVO  SAFE BLEACH  FABRIC TREATMENT  ROSA
1          NaN  ...      NaN    NaN          NaN               NaN   NaN
2          NaN  ...      NaN    NaN          NaN               NaN   NaN
3          NaN  ...      NaN    NaN          NaN               NaN   NaN
4          NaN  ...      NaN    NaN          NaN               NaN   NaN

  ID_CATEGORY  YEAR  MONTH  WEEK_NUMBER       DATE
0         NaN  2022      8           34 2022-08-28
1         NaN  2022      8           34 2022-08-28
2         NaN  2022      8           34 2022-08-28
3         NaN  2022      8           34 2022-08-28
4         NaN  2022      8           34 2022-08-28

[5 rows x 22 columns]

In [63]:
#Exportar
final_df.to_csv(r"C:\Users\Nefi\OneDrive\Documentos\09-EBAC\Python\Referencia\Proyecto\sales_consolidado.csv", 
                index=False)